print("Tipos de Dados")
print("Inteiros")
print(1+10)
print()
print("Flutuantes")
print(1.5+10.5)
print()
print("Strings")
print("Olá, Mundo!") 
print("Python é divertido!")
print()
print("Booleanos")
print(True)
print(False)
print()
print("Listas")
print([1, 2, 3, 4, 5])
print(["Python", "Java", "C++"])
print()
print("Tuplas")
print((1, 2, 3))
print(("Python", "Java", "C++"))
print()
print("Dicionários")
print({"nome": "Alice", "idade": 30})
print({"linguagem": "Python", "ano": 2023})
print()
print("Conjuntos")
print({1, 2, 3, 4, 5})
print({"Python", "Java", "C++"})
print()